# Utilise une image de Node.js
FROM node:14

# Crée le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copie les fichiers nécessaires
COPY package*.json ./
COPY src ./src

# Installe les dépendances
RUN npm install

# Expose le port sur lequel l'application écoute
EXPOSE 8000

# Commande pour lancer l'application
CMD ["node", "src/count-server.js"]